### ISSUE TITLE
NullPointerException at showMenu()

### ISSUE THREAD

**Issue by K4llle** [Gregadeaux/android-fly-in-app-navigation#2]
I get a NullPointerException at showMenu(). mFanView, mTintMenu and mMainMenu are null when executing the sample code... Are there any sources for the sample app?

06-24 21:07:44.536: E/AndroidRuntime(858): FATAL EXCEPTION: main
06-24 21:07:44.536: E/AndroidRuntime(858): java.lang.NullPointerException
06-24 21:07:44.536: E/AndroidRuntime(858):  at com.deaux.fan.FanView.showMenu(FanView.java:57)
06-24 21:07:44.536: E/AndroidRuntime(858):  at de.tk.fansample.FanSampleActivity$1.onClick(FanSampleActivity.java:28)
06-24 21:07:44.536: E/AndroidRuntime(858):  at android.view.View.performClick(View.java:3511)
06-24 21:07:44.536: E/AndroidRuntime(858):  at android.view.View$PerformClick.run(View.java:14105)
06-24 21:07:44.536: E/AndroidRuntime(858):  at android.os.Handler.handleCallback(Handler.java:605)
06-24 21:07:44.536: E/AndroidRuntime(858):  at android.os.Handler.dispatchMessage(Handler.java:92)
06-24 21:07:44.536: E/AndroidRuntime(858):  at android.os.Looper.loop(Looper.java:137)
06-24 21:07:44.536: E/AndroidRuntime(858):  at android.app.ActivityThread.main(ActivityThread.java:4424)
06-24 21:07:44.536: E/AndroidRuntime(858):  at java.lang.reflect.Method.invokeNative(Native Method)
06-24 21:07:44.536: E/AndroidRuntime(858):  at java.lang.reflect.Method.invoke(Method.java:511)
06-24 21:07:44.536: E/AndroidRuntime(858):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
06-24 21:07:44.536: E/AndroidRuntime(858):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
06-24 21:07:44.536: E/AndroidRuntime(858):  at dalvik.system.NativeStart.main(Native Method)

**Comment by Gregadeaux** [comment]
Is this just uploading the apk from the repository or your own sample app? If it is your own, be sure to call setViews before you try and call showMenu.

**Comment by K4llle** [comment]
It's my own. I tried the one from google play and it works. I just copied the sample code and added a "fan" layout. In "test.xml" I changed the app namespace to mine... I changed the click and unclick methods to a onclicklistener...

**Comment by Gregadeaux** [comment]
I apologize for the currently incomplete documentation on this.

You need to call setViews before you can call showMenu. setViews takes the id's of the two layouts you are going to use for that app screen. So you need to have something like this somewhere in your app before you can call fan.showMenu():

fan = (FanView) findViewById(R.id.fan_view);
fan.setViews(R.layout.main, R.layout.fan);

Do you have two other views defined? The purpose of this library is to give you, the developer, complete control of the look of your app and it's menu. You are not restricted to a list or an image. You can do whatever you want. As such, you need to do a little more work on your end to define the layouts. But you can define the layouts like they were independent screens. 

I will upload my sample code one I get home this afternoon in a zip included in the repository.

If you have any suggestions on how this _should_ work, please feel free to tell me either in here or in my email listed on the Readme. If you use my library in a published app, please let me know and I will list your app on my readme or in my wiki as well! Thanks!

**Comment by K4llle** [comment]
My code:

package de.tk.fansample;

import com.deaux.fan.FanView;

import android.app.Activity;
import android.os.Bundle;
import android.util.Log;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;

public class FanSampleActivity extends Activity {
    /*\* Called when the activity is first created. */

```
private FanView fan;

@Override
protected void onCreate(Bundle savedInstanceState) {
    setContentView(R.layout.test);
    fan = (FanView) findViewById(R.id.fan_view);
    fan.setViews(R.layout.main, R.layout.fan);

    Log.d("main", "views set");
    super.onCreate(savedInstanceState);
}

@Override
public boolean onCreateOptionsMenu(Menu menu) {
    MenuInflater inflater = getMenuInflater();
    inflater.inflate(R.menu.menu, menu);

    return true;
}

@Override
public boolean onOptionsItemSelected(MenuItem item) {
    switch (item.getItemId()) {
    case R.id.item1:
        fan.showMenu();
        break;
    default:
        break;
    }

    return true;
}
```

}

test.xml:

<?xml version="1.0" encoding="utf-8"?>
<com.deaux.fan.FanView 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res/de.tk.fansample"
    android:id="@+id/fan_view"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:orientation="vertical" 
    app:menuSize="200dp"/>

main.xml and fan.xml are just linearlayouts with a textview in it... Strange...

**Comment by Gregadeaux** [comment]
Hmmm. That's weird. I'm assuming your xml looks like this and not what you posted.
<?xml version="1.0" encoding="utf-8"?>
< com.deaux.fan.FanView 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res/de.tk.fansample"
    android:id="@+id/fan_view"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:orientation="vertical" 
    app:menuSize="200dp"/>

I used your sample code but just added an onClick attribute instead of using the menu and it works fine.

Ah github removes that header for some reason...

**Comment by K4llle** [comment]
Ok. I tried an old version with your sample code in the same project as the library and it works.... If the library is just referenced i get problems. Maybe my project is kind of bricked.... Why don't you put your .project files on git? It's not importable with eclipse without that... 

But, this library is really great. When my prototype app is ready I will contact you again that you know how it's used :D

**Comment by Gregadeaux** [comment]
I'll look into doing something like that. I'm not positive putting in the .project files will help as I'm not sure how related they are to my specific file system. I've had problems in the past with shared repositories and eclipse files. But I'll dig into it further as well as uploading a zip with my sample application this evening.

Thanks for your support! (Please close this issue if you feel it has been resolved)

**Comment by K4llle** [comment]
NOW! It's resolved! Me (i*iot) removed the click(View v) and unclick(View v) methods... Without the the exception occurs. With them inside everything works well... Thanks for that great lib!

**Comment by K4llle** [comment]
Closed!
