### ISSUE TITLE
Problem importing

### ISSUE THREAD

**Issue by quentin23soleil** [Gregadeaux/android-fly-in-app-navigation#4]
Hello,

When I import existing project into workspace, i get this error and i can't do anything.
Do you have a fix?

[2012-07-24 17:35:19 - android-fly-in-app-navigation] /android-fly-in-app-navigation/gen already exists but is not a source folder. Convert to a source folder or rename it.

**Comment by Gregadeaux** [comment]
Hmmm with stuff like this I usually try doing a Clean on the project. Have you tried that?

**Comment by quentin23soleil** [comment]
The thing is i get the error when i import your lib in existing project. No
relation with my project.

On Tue, Jul 24, 2012 at 5:37 PM, Greg Billetdeaux <
reply@reply.github.com

> wrote:
> 
> Hmmm with stuff like this I usually try doing a Clean on the project. Have
> you tried that?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/Gregadeaux/android-fly-in-app-navigation/issues/4#issuecomment-7210662

## 

Quentin DOMMERC
Freelance dans le dev. Android
Google Student Ambassador
Etudiant EPITECH
Mon webCV http://quentin-dommerc.fr/
Mon G+ https://plus.google.com/u/0/114924336724028319172
Follow me on Twitter http://twitter.com/kentin_dommerc

**Comment by Gregadeaux** [comment]
The way I've done it, and the way I suggest, is to import it into a new project, then add it to your project as a library. If the import gives you gen errors, I do a clean on the library project and see if that fixes anything. For some reason, eclipse doesn't always generate the R.java file like it should.

**Comment by quentin23soleil** [comment]
Re-imported the project, cleaned, still the same error :/

**Comment by Gregadeaux** [comment]
Try this. http://stackoverflow.com/questions/6185600/android-fbreaderj-gen-already-exists-but-is-not-a-source-folder-convert-to-a-s

**Comment by quentin23soleil** [comment]
Worked. Perfect.

**Comment by quentin23soleil** [comment]
New problem from the old one.

None of my R.\* is not recognized because i imported the one from the lib due to the SO fix :/

**Comment by serggl** [comment]
for me fixing the problem was to correct .classpath file to:

``` xml
<classpath>
    <classpathentry kind="src" path="src"/>
    <classpathentry kind="src" path="gen"/>
    <classpathentry kind="con" path="com.android.ide.eclipse.adt.ANDROID_FRAMEWORK"/>
    <classpathentry kind="con" path="com.android.ide.eclipse.adt.LIBRARIES"/>
    <classpathentry kind="output" path="bin/classes"/>
</classpath>
```

**Comment by quentin23soleil** [comment]
Not working :/

**Comment by serggl** [comment]
you need to reload eclipse in order to reload .classpath

**Comment by quentin23soleil** [comment]
I had the same .classpath file. No need to change it though.
