### ISSUE TITLE
setcontentview

### ISSUE THREAD

**Issue by quentin23soleil** [Gregadeaux/android-fly-in-app-navigation#5]
Hi _again_,

Now, when i do this : 

```
    setContentView(R.layout.menu_slider);
    fan = (FanView) findViewById(R.id.fan_view);
    fan.setViews(R.layout.activity_play, R.layout.menu_slider);
```

I just lose control to the activity_play widgets, right? How can i do this if imageTop is in the layout activity_play?

```
    top = (ImageView) findViewById(R.id.imageTop);
```

**Comment by Gregadeaux** [comment]
That should work fine. No reason that shouldn't work by just putting that last line right after the other three.

**Comment by quentin23soleil** [comment]
It does, my fault.

On Wed, Jul 25, 2012 at 2:58 PM, Greg Billetdeaux <
reply@reply.github.com

> wrote:
> 
> That should work fine. No reason that shouldn't work by just putting that
> last line right after the other three.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/Gregadeaux/android-fly-in-app-navigation/issues/5#issuecomment-7248207

## 

Quentin DOMMERC
Freelance dans le dev. Android
Google Student Ambassador
Etudiant EPITECH
Mon webCV http://quentin-dommerc.fr/
Mon G+ https://plus.google.com/u/0/114924336724028319172
Follow me on Twitter http://twitter.com/kentin_dommerc
